---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-infra-secrets
  labels:
    app: {{ .Release.Name }}-AllApps
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    app: {{ .Release.Name }}-AllApps
    app.business.client: {{ .Values.ClientName }}
    app.mqtt.event.trigger: {{ .Values.traceID }}
type: Opaque    
data:
  mariadb_username: YWRtaW4K # admin
  mariadb_password: {{ randAlphaNum 32 | b64enc | quote }}
  mariadb_root_password: {{ randAlphaNum 32 | b64enc | quote }}
  #
  slack_webhook: {{ randAlphaNum 32 | b64enc | quote }}