---
apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: {{ .Release.Name }}-producer
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
    filter.by.port.name: "true"
spec:
  selector:
    app: {{ .Release.Name }}-producer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: monitoring
      protocol: TCP
      port: 9090
      targetPort: 9090



# ---
# apiVersion: v1
# kind: ConfigMap
# metadata: 
#   name: producer-cm
#   namespace: default
#   labels:
#     app: producer
#     environment: development
#   annotations:
#     app: producer
#     app.business.client: 'client-001'
#     app.mqtt.event.trigger: '1234567890'    
# data:
#   # /usr/share/nginx/html
#   index.html: |-
#       <!DOCTYPE html>
#       <html>
#       <head>
#       <meta name="viewport" content="width=device-width, initial-scale=1">
#       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
#       <link rel="stylesheet" href="./custom.css">
#       <style>
#             body {
#               font-family: Arial;
#               font-size: 12px;
#               padding: 8px;
#               width: 30%;
#               background-image: url('https://img.freepik.com/free-vector/gradient-futuristic-background-with-connection-concept_23-2149104857.jpg');
#               background-size: cover; /* Ajusta el tamaño de la imagen */
#               background-position: center; /* Centra la imagen */  
#             }
#             h1 {
#               text-align: center;
#               color: black; /* Color del texto */
#             }
#             input[type=text] {
#               width: 100%;
#               margin-bottom: 5px;
#               padding: 5px;
#               color: black; /* Color del texto */
#             }
#             .select {
#               width: 100%;
#               margin-bottom: 5px;
#               padding: 5px;
#             }
#             .icon-container {
#               margin-bottom: 20px;
#               padding: 7px 0;
#             }
#             .btn {
#               background-color: #04AA6D;
#               color: white;
#               padding: 12px;
#               margin: 10px 0;
#               border: none;
#               width: 100%;
#               border-radius: 3px;
#               cursor: pointer;
#             }
#       </style>
#       </head>
#       <body>
#       <div class="row">
#         <div class="col-75">
#           <div class="container">
#             <form action="" method="post" class="" id="formulario" >
#       <div align="center">
#       <img src="https://img.freepik.com/free-vector/gradient-futuristic-background-with-connection-concept_23-2149104857.jpg"> 
#       <br>
#       </div>
#           <h1>Product</h1>
#               <div class="container">
#                 <div class="col-75">
#                   <label for="client"><i class="fa fa-tag"></i> Client Name</label><input type="text" id="client" name="client" placeholder="" required="required">
#                   <label for="product"><i class="fa fa-archive"></i> Product</label><select id="product" name="product"  class="select">
#                           <option value="nginx">nginx</option>
#                           <option value="wordpress">wordpress</option>
#                           <option value="moodle">Moodle</option>
#                           </select>
#                   <label for="fname"><i class="fa fa-sitemap"></i> Environment</label><select id="environment" name="environment"  class="select">
#                           <option value="development">Development</option>
#                           <option value="stage">Stage</option>
#                           <option value="production">Production</option>
#                           </select>
#                   <label for="archtype"><i class="fa fa-cloud"></i> Architecture Type</label><select id="archtype" name="archtype" class="select">
#                         <option value="saas">Software as a Service (SaaS)</option>
#                         <option value="paas">Platform as a Service (PaaS)</option>                        
#                         <option value="edge">Edge (Cloud)</option>
#                         <option value="classic">Classic Old (On-Prem)</option>
#                         </select>
#                   <label for="hardware"><i class="fa fa-cog"></i> Hardware</label><select id="hardware" name="hardware"  class="select">
#                         <option value="shared">Hardware Classic (Shared - No extra cost allocated)</option>
#                         <option value="dedicated">Hardware Dedicated (Extra cost allocated)</option>
#                         </select>               
#               </div>
#             </div>
#
#               <div class="row">
#                 <div class="col-50">
#                   <h1>Billing Address</h1>
#                   <label for="fname"><i class="fa fa-user"></i> Full Name</label><input type="text" id="fname" name="firstname" placeholder="Ned Flanders" required="required">
#                   <label for="email"><i class="fa fa-envelope"></i> Email</label><input type="text" id="email" name="email" placeholder="nedf@businessmail.com" required="required">
#                   <label for="adr"><i class="fa fa-address-card-o"></i> Address</label><input type="text" id="adr" name="address" placeholder="Avenida Siempreviva 744" required="required">
#                   <label for="city"><i class="fa fa-institution"></i> City</label><input type="text" id="city" name="city" placeholder="Springfield" required="required">

#                   <div class="row">
#                     <div class="col-50">
#                       <label for="state">State</label><input type="text" id="state" name="state" placeholder="LA" required="required">
#                     </div>
#                     <div class="col-50">
#                       <label for="zip">Zip</label><input type="text" id="zip" name="zip" placeholder="10001" required="required">
#                     </div>
#                   </div>
#                 </div>

#                 <div class="col-50">
#                   <h1>Payment</h1>
#                 <div align="center">
#                   <div class="icon-container">
#                     <i class="fa fa-cc-visa" style="color:navy;"></i>
#                     <i class="fa fa-cc-amex" style="color:blue;"></i>
#                     <i class="fa fa-cc-mastercard" style="color:red;"></i>
#                     <i class="fa fa-cc-discover" style="color:orange;"></i>
#                     </div>
#                   </div>
#                   <label for="cardname">Name on Card</label><input type="text" id="cardname" name="cardname" placeholder="Ned Flanders" required="required">
#                   <label for="cardnumber">Credit card number</label><input type="text" id="cardnumber" name="cardnumber" placeholder="1111-2222-3333-4444" required="required">
#                   <label for="cardexpmonth">Exp Month</label><input type="text" id="cardexpmonth" name="cardexpmonth" placeholder="September" required="required">
#                   <div class="row">
#                     <div class="col-50">
#                       <label for="cardexpyear">Exp Year</label><input type="text" id="cardexpyear" name="cardexpyear" placeholder="2050" required="required">
#                     </div>
#                     <div class="col-50">
#                       <label for="cardcvv">CVV</label>
#                       <input type="text" id="cardcvv" name="cardcvv" placeholder="666" required="required">
#                     </div>
#                   </div>
#                 </div>

#               </div>
#               <input type="submit" value="Continue to checkout" class="btn">
#             </form>
#           </div>
#         </div>

#       </div>

#       </body>
#       </html>





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: {{ .Release.Name }}-producer
    app.depends: {{ .Release.Name }}-rabbitmq
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-producer    
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-producer
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
    spec:
      containers:
        - name: {{ .Release.Name }}-producer
          image: {{ .Values.producer.image }}:{{ .Values.producer.tag }}
          imagePullPolicy: {{ .Values.producer.imagePullPolicy }}
          env:
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: {{ .Values.rabbitmq.configs.mqttvhost }}
          - name: queue
            value: {{ .Values.rabbitmq.configs.queue }}
          - name: destination_queue
            value: {{ .Values.rabbitmq.configs.destination_queue }}
          - name: destination_RK
            value: {{ .Values.rabbitmq.configs.destination_rk }}
          - name: mqttuser
            value: {{ .Values.rabbitmq.auth.username }}
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password              
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5                
      #     volumeMounts:
      #       - name: producer-cm
      #         mountPath: /app/templates/
      # volumes:
      #   #-------------------------        
      #   - name: producer-cm
      #     configMap:
      #       name: producer-cm            
