---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}-webserver
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}
spec:
  selector:
    app: webserver
  ports:
    - name: http
      protocol: TCP     
      port: 8080
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: {{ .Release.Name }}-webserver
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: 'true'
    app.mqtt.event.trigger: {{ .Values.traceID }}   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webserver
      environment: {{ .Values.environment }}
      app.business.client: {{ .Values.ClientName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webserver
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
      annotations:
        app.version: {{ .Values.webserver.image }}:{{ .Values.webserver.tag }}
        app.mqtt.event.trigger: {{ .Values.traceID }}      
        environment: {{ .Values.environment }} 
    spec:
      containers:
        - name: webserver
          image: {{ .Values.webserver.image }}:{{ .Values.webserver.tag }}
          imagePullPolicy: {{ .Values.webserver.imagePullPolicy }}
          ports:
            - containerPort: 80          