---
apiVersion: v1
kind: Service
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: dbwriter
    app.depends: rabbitmq  
    environment: development
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
    app: dbwriter
    app.depends: rabbitmq  
    app.business.client: 'client-001'
    app.mqtt.event.trigger: '1234567890'    
spec:
  selector:
    app: dbwriter
  ports:
    - name: metrics
      protocol: TCP     
      port: 9090 




#  PENDING 
#
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: secret-dbwriter
#  namespace: default
#type: Opaque
#data:
#  username: YWRtaW4= # admin
#  password: YWRtaW4= # admin



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: dbwriter
    app.depends: rabbitmq  
    environment: development
  annotations:
    prometheus.io/scrape: 'true'
    app: dbwriter
    app.depends: rabbitmq  
    app.business.client: 'client-001'
    app.mqtt.event.trigger: '1234567890'    
    app.owner: 'jpradoar'
    app.imageregistry: 'https://hub.docker.com/repository/docker/jpradoar/mqtt-dbwriter/'   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbwriter
  template:
    metadata:
      labels:
        app: dbwriter
    spec:
      containers:
        - name: dbwriter
          image: jpradoar/mqtt-dbwriter:2023.05
          imagePullPolicy: Always   
          env:
          - name: mqtthost
            value: "rabbitmq"
          - name: mqttvhost
            value: "/"
          - name: mqttuser
            value: "admin" 
          - name: mqttpass
            value: "admin" 
          - name: queue
            value: "clients"
          - name: mysql_host
            value: "mariadb"
          - name: mysql_user
            value: "admin"
          - name: mysql_pass
            value: "admin"
          - name: mysql_db
            value: "clients"