---
- name: Deploy EDA Demo
  hosts: all
  # become: true
  # become_method: sudo
  # become_user: admin

  vars:
    OS_USER: 'admin'


  tasks:

      - name: echo hola
        ansible.builtin.shell: |
            echo "hola"
        args:
          executable: /bin/bash